### ISSUE TITLE
Disable captive portal?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#34]
Hi Magnus, to disable the captive portal, is it sufficient to comment these lines?

```
  ap:
    ssid: "xxxxxxxx Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxxxxxxx"

captive_portal:

```

Thank you! :)

PS: Ups, maybe I'm just looking at the "wrong" ESP32s of mine, which has not your inetbox2mqqt. If that's the case, ashes on my head, and please forgive me my mistake. *blush*
